### ISSUE TITLE
build error in rt-thread

### ISSUE THREAD

**Issue by shmm91** [wuhanstudio/micro_ros#2]
Thank you for you great work! This is my build issue in rt-thread. 
The hardware is STM32F765IIK.
The config on micro_ros is:
Device type:UART
ARCH CPU:Cortex M7(fpv5-d16-soft)
serial device name:uart3
Version:foxy

Here are build errors:
arm-none-eabi-gcc "../libraries/STM32F7xx_HAL/STM32F7xx_HAL_Driver/Src/stm32f7xx_hal_cryp_ex.c"
In file included from ../packages/micro_ros-foxy/src/rtt_serial_transports.c:52:0:
../packages/micro_ros-foxy/src/micro_ros_rtt.h:20:44: warning: 'struct timespec' declared inside parameter list
 int clock_gettime(clockid_t unused, struct timespec *tp);
                                            ^
../packages/micro_ros-foxy/src/micro_ros_rtt.h:20:44: warning: its scope is only this definition or declaration, which is probably not what you want
../packages/micro_ros-foxy/src/rtt_serial_transports.c:71:5: error: conflicting types for 'clock_gettime'
 int clock_gettime(clockid_t unused, struct timespec *tp)
     ^
In file included from ../packages/micro_ros-foxy/src/rtt_serial_transports.c:52:0:
../packages/micro_ros-foxy/src/micro_ros_rtt.h:20:5: note: previous declaration of 'clock_gettime' was here
 int clock_gettime(clockid_t unused, struct timespec *tp);
     ^
make: *** [packages/micro_ros-foxy/src/subdir.mk:30: packages/micro_ros-foxy/src/rtt_serial_transports.o] Error 1
make: *** Waiting for unfinished jobs....
"make -j12 all" terminated with exit code 2. Build might be incomplete.

Could you give me some advise? Thank you!

**Comment by wuhanstudio** [comment]
Hi,

The build log includes several warnings, but no error. Maybe the actual error is somewhere else.

**Comment by shmm91** [comment]
> Hi,
> 
> The build log includes several warnings, but no error. Maybe the actual error is somewhere

**Comment by shmm91** [comment]
> Hi,
> 
> The build log includes several warnings, but no error. Maybe the actual error is somewhere else.

You can watch rtt_serial_transports.c:71:5: error: conflicting types for 'clock_gettime' message. May somewhere conflict with clock_gettime.

**Comment by wuhanstudio** [comment]
Sorry I did not notice the error message. This can be fixed by adding another hearder file because `struct timespec`  is undefined:

```
#include <sys/time.h>
```

or

```
#include <time.h>
```

**Comment by shmm91** [comment]
> 

Thank you, it's worked!
