### ISSUE TITLE
使用M7库问题

### ISSUE THREAD

**Issue by baolixin123** [wuhanstudio/micro_ros#3]
1 开发RT1052野火开发板，配置时使用M7（FPV5-D16-HEARD）
![9081f386c907ab22782e804d7898945](https://user-images.githubusercontent.com/97417496/172084070-c9f8e4e1-b148-477f-bf13-e8769e7ea1be.png)
2 编译可以通过，但仿真的时候运行到rclc初始化没有过，也没有返回值。直接跑死到z下面这部分了.
![69b639cb44c7ac76258fe2cf8a1ad92](https://user-images.githubusercontent.com/97417496/172084230-c9872204-041b-4c04-bbdf-779d06b27cb4.png)
3 这个支持对应的 libmicroros.a可以支持RT1052野火开发板吗

**Comment by wuhanstudio** [comment]
hello，現在是有 RT1062 的編譯配置：

https://github.com/wuhanstudio/micro_ros/blob/master/extras/library_generation/teensy4_toolchain.cmake

上面鏈接是選中 M7（FPV5-D16-HEARD）后的編譯選項，你可以看看針對 RT1052 需不需要修改編譯選項，並重新編譯生成  libmiroros.a

https://micro.ros.org/docs/tutorials/advanced/create_custom_static_library/

**Comment by baolixin123** [comment]
运行micro-ros库需要使用多大内存呢，我看了下RT1062和RT1052的区别只有内存更大了的区别。并且我使用了M0的colcon_verylowmem.meta
编译，同样会出现这样的问题。



调试发现到这里的时候停止运行了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wuhanstudio/micro_ros"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月6日(星期一) 晚上11:35
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wuhanstudio/micro_ros] 使用M7库问题 (Issue #3)





 
hello，現在是有 RT1062 的編譯配置：
 
https://github.com/wuhanstudio/micro_ros/blob/master/extras/library_generation/teensy4_toolchain.cmake
 
上面鏈接是選中 M7（FPV5-D16-HEARD）后的編譯選項，你可以看看針對 RT1052 需不需要修改編譯選項，並重新編譯生成  libmiroros.a
 
https://micro.ros.org/docs/tutorials/advanced/create_custom_static_library/

**Comment by wuhanstudio** [comment]
你好，micro_ros 本身占用内存不大，

- 如果是串口通信，STM32F103RC (48KB SRAM) 也可以稳定运行
- 如果是 UDP 通信，主要是网络协议栈会耗费更多的内存

可以先使用串口测试看会不会死机，这是 micro_ros 官方支持的开发板列表：

https://micro.ros.org/docs/overview/hardware/

**Comment by shmm91** [comment]
@baolixin123 ,你的问题解决了么？我遇见和你一样的问题，程序同样是卡死在rclc_support_init函数。我这边用的是stm32f407ZGTx  CortexM4。

**Comment by wuhanstudio** [comment]
> @baolixin123 ,你的问题解决了么？我遇见和你一样的问题，程序同样是卡死在rclc_support_init函数。我这边用的是stm32f407ZGTx CortexM4。

你好，你的问题在这个 issue 里应当解决了，主要是  ip 的配置 和 lwip 的版本问题：

https://github.com/wuhanstudio/micro_ros/issues/4

**Comment by wuhanstudio** [comment]
最近我更新了 micro_ros 在 galactic 和 humble 上的支持，也增加了 Cortex-M7 各个编译选项下的静态库：

- fpv5-sp-d16-hard
- fpv5-sp-d16-softfp
- fpv5-d16-hard
- fpv5-d16-soft
