### ISSUE TITLE
micro_ros_pub_int32_udp运行，系统卡在set_microros_udp_transports("192.168.1.30", 9999);

### ISSUE THREAD

**Issue by shmm91** [wuhanstudio/micro_ros#4]
你好，在rtthred上编译完，采用microros udp模式，运行example时出错
![microros](https://user-images.githubusercontent.com/13912909/186603979-6736e653-bc74-426c-9fd9-3d95cb3d8345.PNG)
。

**Comment by wuhanstudio** [comment]
你好，

这里你的 IP 设置错了，这里的参数是 PC 上运行的 micro-ros-agent 的 IP，建立 RTT 和 PC 的通信。

看代码里，你设置的是 RT-Thread 的 IP (192.168.1.30)，这样成了 RTT 自己和自己建立连接，所以卡住了。

```
set_microros_udp_transports("替换这里的 IP", 9999);
```

**Comment by shmm91** [comment]
> 你好，
> 
> 这里你的 IP 设置错了，这里的参数是 PC 上运行的 micro-ros-agent 的 IP，建立 RTT 和 PC 的通信。
> 
> 看代码里，你设置的是 RT-Thread 的 IP (192.168.1.30)，这样成了 RTT 自己和自己建立连接，所以卡住了。
> 
> ```
> set_microros_udp_transports("替换这里的 IP", 9999);
> ```

你好，我测试过，当时我理解的是，set_microros_udp_transports这里设备本机ip和端口。后来我改过了，也是同样的问题。同时，我测试了串口通信，也同样卡住了。

**Comment by shmm91** [comment]
> 你好，
> 
> 这里你的 IP 设置错了，这里的参数是 PC 上运行的 micro-ros-agent 的 IP，建立 RTT 和 PC 的通信。
> 
> 看代码里，你设置的是 RT-Thread 的 IP (192.168.1.30)，这样成了 RTT 自己和自己建立连接，所以卡住了。
> 
> ```
> set_microros_udp_transports("替换这里的 IP", 9999);
> ```

下面是改过之后，提示的错误。
![2](https://user-images.githubusercontent.com/13912909/187135011-8b8bcfba-c531-4222-b10e-a40d95625e10.PNG)

**Comment by wuhanstudio** [comment]
看这个报错应当是开发板的 UDP 通信和串口通信没有配置好，例如串口驱动没有初始化成功 (micro_ros 需要用单独的串口接到电脑上，所以建议在 Ubuntu 里测试串口)。

另外在建立连接前，需要确保 micro_ros_agent 已经在 PC 上运行了。

**Comment by shmm91** [comment]
> 看这个报错应当是开发板的 UDP 通信和串口通信没有配置好，例如串口驱动没有初始化成功 (micro_ros 需要用单独的串口接到电脑上，所以建议在 Ubuntu 里测试串口)。
> 
> 另外在建立连接前，需要确保 micro_ros_agent 已经在 PC 上运行了。

问题找见了，是lwIP的库版本问题，低版本的会出现上述问题，换成高版本的就可以了。
