### ISSUE TITLE
MicroROS　链接问题

### ISSUE THREAD

**Issue by weblxj** [wuhanstudio/micro_ros#9]
我下载galactic-gcc-10的micro ROS版本，也可以编译，但是碰到一个LINK的错误。麻烦您指点下可能是什么问题：

linking...

arm-none-eabi-gcc -T "E:\RT-ThreadStudio\workspace\imxrt1052-fire-pro_ROS2_DDS\board\linker_scripts\link.lds" -nostartfiles -Xlinker --gc-sections -L"E:\RT-ThreadStudio\workspace\imxrt1052-fire-pro_ROS2_DDS\packages\micro_ros-galactic-gcc-10\src\cortex-m7\fpv5-d16-hard" -Wl,-Map,"rtthread.map" -Xlinker --cref -mcpu=cortex-m7 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=hard -ffunction-sections -fdata-sections -lm -lgcc -lc -nostartfiles -Wl,--gc-sections,-Map=rtthread.map,-cref,-u,Reset_Handler -o "rtthread.elf"  ./rt-thread/src/clock.o ./rt-thread/src/components.o ./rt-thread/src/device.o ./rt-thread/src/idle.o ./rt-thread/src/ipc.o ./rt-thread/src/irq.o ./rt-thread/src/kservice.o ./rt-thread/src/memheap.o ./rt-thread/src/mempool.o ./rt-thread/src/object.o ./rt-thread/src/scheduler.o ./rt-thread/src/thread.o ./rt-thread/src/timer.o  ./rt-thread/libcpu/arm/cortex-m7/context_gcc.o ./rt-thread/libcpu/arm/cortex-m7/cpu_cache.o ./rt-thread/libcpu/arm/cortex-m7/cpuport.o  ./rt-thread/libcpu/arm/common/backtrace.o ./rt-thread/libcpu/arm/common/div0.o ./rt-thread/libcpu/arm/common/showmem.o  ./rt-thread/components/utilities/ulog/backend/console_be.o  ./rt-thread/components/utilities/ulog/ulog.o  ./rt-thread/components/net/sal/src/sal_socket.o  ./rt-thread/components/net/sal/socket/net_netdb.o ./rt-thread/components/net/sal/socket/net_sockets.o  ./rt-thread/components/net/sal/impl/af_inet_lwip.o  ./rt-thread/components/net/sal/dfs_net/dfs_net.o  ./rt-thread/components/net/netdev/src/netdev.o ./rt-thread/components/net/netdev/src/netdev_ipaddr.o  ./rt-thread/components/net/lwip/port/ethernetif.o ./rt-thread/components/net/lwip/port/sys_arch.o  ./rt-thread/components/net/lwip/lwip-2.0.3/src/netif/ethernet.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/netif/lowpan6.o  ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/ipv4/autoip.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/ipv4/dhcp.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/ipv4/etharp.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/ipv4/icmp.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/ipv4/igmp.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/ipv4/ip4.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/ipv4/ip4_addr.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/ipv4/ip4_frag.o  ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/def.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/dns.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/inet_chksum.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/init.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/ip.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/memp.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/netif.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/pbuf.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/raw.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/stats.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/sys.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/tcp.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/tcp_in.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/tcp_out.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/timeouts.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/core/udp.o  ./rt-thread/components/net/lwip/lwip-2.0.3/src/apps/ping/ping.o  ./rt-thread/components/net/lwip/lwip-2.0.3/src/api/api_lib.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/api/api_msg.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/api/err.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/api/netbuf.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/api/netdb.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/api/netifapi.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/api/sockets.o ./rt-thread/components/net/lwip/lwip-2.0.3/src/api/tcpip.o  ./rt-thread/components/libc/posix/io/poll/poll.o ./rt-thread/components/libc/posix/io/poll/select.o  ./rt-thread/components/libc/posix/delay/delay.o  ./rt-thread/components/libc/compilers/newlib/syscalls.o  ./rt-thread/components/libc/compilers/common/stdlib.o ./rt-thread/components/libc/compilers/common/time.o  ./rt-thread/components/finsh/cmd.o ./rt-thread/components/finsh/msh.o ./rt-thread/components/finsh/msh_file.o ./rt-thread/components/finsh/shell.o  ./rt-thread/components/drivers/serial/serial.o  ./rt-thread/components/drivers/phy/phy.o  ./rt-thread/components/drivers/misc/pin.o  ./rt-thread/components/drivers/ipc/completion.o ./rt-thread/components/drivers/ipc/dataqueue.o ./rt-thread/components/drivers/ipc/pipe.o ./rt-thread/components/drivers/ipc/ringblk_buf.o ./rt-thread/components/drivers/ipc/ringbuffer.o ./rt-thread/components/drivers/ipc/waitqueue.o ./rt-thread/components/drivers/ipc/workqueue.o  ./rt-thread/components/drivers/cputime/cputime.o  ./rt-thread/components/drivers/can/can.o  ./rt-thread/components/dfs/src/dfs.o ./rt-thread/components/dfs/src/dfs_file.o ./rt-thread/components/dfs/src/dfs_fs.o ./rt-thread/components/dfs/src/dfs_posix.o  ./packages/micro_ros-galactic-gcc-10/src/identifier.o ./packages/micro_ros-galactic-gcc-10/src/rtt_serial_transports.o ./packages/micro_ros-galactic-gcc-10/src/rtt_udp_transport.o ./packages/micro_ros-galactic-gcc-10/src/string_utilities.o ./packages/micro_ros-galactic-gcc-10/src/type_utilities.o  ./packages/micro_ros-galactic-gcc-10/examples/micro_ros_ping_pong.o ./packages/micro_ros-galactic-gcc-10/examples/micro_ros_pub_int32.o ./packages/micro_ros-galactic-gcc-10/examples/micro_ros_pub_sub_int32.o ./packages/micro_ros-galactic-gcc-10/examples/micro_ros_sub_int32.o  ./libraries/drivers/drv_can.o ./libraries/drivers/drv_eth.o ./libraries/drivers/drv_gpio.o ./libraries/drivers/drv_uart.o  ./libraries/MIMXRT1050/MIMXRT1052/gcc/startup_MIMXRT1052.o  ./libraries/MIMXRT1050/MIMXRT1052/drivers/fsl_cache.o ./libraries/MIMXRT1050/MIMXRT1052/drivers/fsl_clock.o ./libraries/MIMXRT1050/MIMXRT1052/drivers/fsl_common.o ./libraries/MIMXRT1050/MIMXRT1052/drivers/fsl_enet.o ./libraries/MIMXRT1050/MIMXRT1052/drivers/fsl_flexcan.o ./libraries/MIMXRT1050/MIMXRT1052/drivers/fsl_gpio.o ./libraries/MIMXRT1050/MIMXRT1052/drivers/fsl_lpuart.o ./libraries/MIMXRT1050/MIMXRT1052/drivers/fsl_os_abstraction_rtthread.o ./libraries/MIMXRT1050/MIMXRT1052/drivers/fsl_xbara.o ./libraries/MIMXRT1050/MIMXRT1052/drivers/fsl_xbarb.o ./libraries/MIMXRT1050/MIMXRT1052/drivers/generic_list.o  ./libraries/MIMXRT1050/MIMXRT1052/system_MIMXRT1052.o  ./board/MCUX_Config/clock_config.o ./board/MCUX_Config/pin_mux.o  ./board/board.o  ./applications/cpuusage.o ./applications/main.o   -lmicroros      -lc      -lm     

e:/rt-threadstudio/repo/extract/toolchain_support_packages/arm/gnu_tools_for_arm_embedded_processors/5.4.1/bin/../lib/gcc/arm-none-eabi/5.4.1/../../../../arm-none-eabi/lib/armv7e-m/fpu\libc.a(lib_a-fini.o): In function `__libc_fini_array':

fini.c:(.text.__libc_fini_array+0x1c): undefined reference to `_fini'

collect2.exe: error: ld returned 1 exit status

make: *** [makefile:81: rtthread.elf] Error 1

"make -j8 all" terminated with exit code 2. Build might be incomplete.

09:53:40 Build Failed. 1 errors, 21 warnings. (took 9s.226ms)

**Comment by wuhanstudio** [comment]
你好，可以试试 RTT 配置里打开 libc
